#!/usr/bin/env python3
"""Builds PKForge's per-game item text: what each game's own bag says about an item, English only.

dexfacts.tsv.gz (build.py) holds one game-neutral line per item; this file holds the games' own
words, which differ (Emerald's Safari Ball works "only in the SAFARI ZONE", Sinnoh's in the Great
Marsh) and follow each game's rules (Soul Dew raises Sp. Atk/Sp. Def until Gen 7, then boosts
Psychic and Dragon moves). PKForge.Domain.ItemTexts shows the open game's line, or the nearest
earlier game's, and falls back to the dexfacts line where no game has text (Gen 1-2).

Source: PokeAPI's CSV data (https://github.com/PokeAPI/pokeapi, data/v2/csv), BSD-3-Clause,
Copyright (c) 2014 Paul Hallett and PokeAPI contributors; the notice travels in the header line.

Usage:
    python3 tools/DexFacts/itemtext.py [csv-dir] [output]
        csv-dir  a directory holding the FILES below (downloaded from PokeAPI master when omitted)
        output   defaults to src/PKForge.Domain/Resources/itemtext.tsv.gz

Deterministic like build.py: sorted rows, no gzip timestamp.

Format (UTF-8 TSV, one record per line; see PKForge.Domain.ItemTextTable):
    #  header / attribution
    G  order                                 (a game with bag text of its own)
    T  order  normalised-english-name  text
       order = PokeAPI's version_groups.order (chronological, side games included). A row is written
       only where an item's text changes from the previous game that has one.
"""
import gzip
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build import ENGLISH, ROOT, clean, load, normalise_name  # noqa: E402

FILES = ["version_groups.csv", "item_names.csv", "item_flavor_text.csv"]
DEFAULT_OUT = os.path.join(ROOT, "src", "PKForge.Domain", "Resources", "itemtext.tsv.gz")


def main():
    csv_dir = sys.argv[1] if len(sys.argv) > 1 and sys.argv[1] != "-" else None
    out = sys.argv[2] if len(sys.argv) > 2 else DEFAULT_OUT
    data = {name: load(csv_dir, name) for name in FILES}

    order = {r["id"]: int(r["order"]) for r in data["version_groups.csv"]}
    names = {r["item_id"]: r["name"] for r in data["item_names.csv"] if r["local_language_id"] == ENGLISH}

    # (name, order) -> text. Same-named rows (regional variants) keep the lowest item id's text.
    texts = {}
    for r in sorted(data["item_flavor_text.csv"], key=lambda r: int(r["item_id"])):
        if r["language_id"] != ENGLISH or r["item_id"] not in names or r["version_group_id"] not in order:
            continue
        # The early games wrote "POKéMON" in capitals; the dex entries normalise it the same way.
        text = clean(r["flavor_text"].replace("\f", " ")).replace("POKéMON", "Pokémon")
        if not any(ch.isalpha() for ch in text):  # placeholders such as "- - -"
            continue
        texts.setdefault((normalise_name(names[r["item_id"]]), order[r["version_group_id"]]), text)

    lines = ["#\tPKForge item text v1 - generated by tools/DexFacts/itemtext.py from PokeAPI data "
             "(github.com/PokeAPI/pokeapi, BSD-3-Clause, (c) 2014 Paul Hallett and PokeAPI contributors)"]
    # Games after the newest data borrow older lines, which is wrong for machines (TM01 teaches a
    # different move in each game): readers ask which games have text of their own.
    for game in sorted({game for (_, game) in texts}):
        lines.append("G\t%d" % game)
    previous = {}
    for (name, game) in sorted(texts):
        text = texts[(name, game)]
        if previous.get(name) == text:
            continue
        previous[name] = text
        lines.append("T\t%d\t%s\t%s" % (game, name, text))

    payload = ("\n".join(lines) + "\n").encode("utf-8")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "wb") as raw:
        with gzip.GzipFile(filename="", mode="wb", fileobj=raw, compresslevel=9, mtime=0) as gz:
            gz.write(payload)
    print("items %d, rows %d -> %s (%d bytes)" % (len(previous), len(lines) - 1, out, os.path.getsize(out)))


if __name__ == "__main__":
    main()
